import turtle
import random as R
from tkinter import messagebox
import os

Graphic = turtle.Screen()
Graphic.setup(1000, 800)
Graphic.title("Happy birthday")
Pen = turtle.Turtle(visible=False)
PenColor = ["lime", "cyan", "blue", "darkblue", "crimson", "gold", "orange", "purple", "deepskyblue", "firebrick",
            "red", "darkgreen", "forestgreen", "limegreen", "lightcyan", "silver", "olive", "gray", "yellow", "turquoise",
            "steelblue"]
Name = turtle.textinput("آشنایی", "اسمت چیه؟")
def EasterEgg():
    Pen.write(f"سلام بر تو, جونم", align="left", font=("Arial", 30))
if Name is None or Name == "":
    messagebox.showerror("نه دیگه, نشد", "من باید اسم تو رو بدونم تا کارم رو انجام بدم")
    os.system("taskkill /f /im python.exe")
FavColor = turtle.textinput("برای سلیقه", "چه رنگی دوست داری؟ (شرط ها: انگلیسی وارد کن, رنگ ها باید توی کتابخانه ترتل باشند, 2 تا رنگ به این صورت: (رنگ,رنگ))")
if FavColor is not None and FavColor != "":
    FavColorUnpack = FavColor.split(",")
try:
    ColorLine = FavColorUnpack[0]
    ColorBG = FavColorUnpack[1]
except (NameError, IndexError):
    ColorLine = PenColor[R.randint(0, len(PenColor) - 1)]
    ColorBG = PenColor[R.randint(0, len(PenColor) - 1)]
if ColorLine in PenColor:
        PenColor.remove(ColorLine)
if ColorBG in PenColor:
        PenColor.remove(ColorBG)
Graphic.bgcolor(ColorBG)
Pen.speed(0)
Dot = 0
while True:
    A = R.randint(-480, 480)
    B = R.randint(-380, 380)
    Pen.penup()
    C = Pen.pos()
    Pen.goto(A, B)
    Pen.pendown()
    if Pen.distance(C) > 500:
        Pen.color(PenColor[R.randint(0, len(PenColor) - 1)])
        Pen.dot(R.randint(20, 100))
        Dot += 1
    if Dot == 30:
        break
Pen.penup()
Pen.goto(400, 340)
Pen.right(90)
Pen.pendown()
Pen.color(ColorLine)
Pen.begin_fill()
Pen.forward(100)
Pen.right(90)
Pen.forward(100)
Pen.right(90)
Pen.forward(20)
Pen.right(90)
Pen.forward(80)
Pen.left(90)
Pen.forward(80)
Pen.right(90)
Pen.forward(20)
Pen.end_fill()
Pen.penup()
Pen.left(90)
Pen.forward(30)
Pen.right(90)
Pen.forward(20)
Pen.dot(30)
Pen.backward(40)
Pen.dot(30)
Pen.backward(80)
Pen.right(90)
Pen.forward(80)
Pen.pendown()
Pen.begin_fill()
Pen.forward(100)
Pen.right(90)
Pen.forward(70)
Pen.right(90)
Pen.forward(20)
Pen.right(90)
Pen.forward(50)
Pen.left(90)
Pen.forward(30)
Pen.left(90)
Pen.forward(50)
Pen.right(90)
Pen.forward(50)
Pen.right(90)
Pen.forward(70)
Pen.end_fill()
Pen.right(90)
Pen.forward(20)
Pen.penup()
Pen.right(90)
Pen.forward(25)
Pen.right(90)
Pen.forward(10)
Pen.left(90)
Pen.pendown()
Pen.fillcolor(ColorBG)
Pen.begin_fill()
Pen.forward(30)
Pen.left(90)
Pen.forward(25)
Pen.left(90)
Pen.forward(40)
Pen.left(90)
Pen.forward(25)
Pen.left(90)
Pen.forward(5)
Pen.end_fill()
Pen.penup()
Pen.forward(90)
Pen.right(90)
Pen.pendown()
Pen.fillcolor(ColorLine)
Pen.begin_fill()
Pen.forward(90)
Pen.left(90)
Pen.forward(20)
Pen.left(90)
Pen.forward(160)
Pen.right(90)
Pen.forward(70)
Pen.right(45)
Pen.forward(65)
Pen.left(90)
Pen.forward(20)
Pen.left(90)
Pen.forward(65)
Pen.right(90)
Pen.forward(65)
Pen.left(90)
Pen.forward(20)
Pen.left(90)
Pen.forward(65)
Pen.right(45)
Pen.forward(90)
Pen.left(90)
Pen.forward(110)
Pen.end_fill()
Pen.left(90)
Pen.penup()
Pen.forward(200)
Pen.left(90)
Pen.forward(40)
Pen.pendown()
Pen.begin_fill()
Pen.forward(60)
Pen.right(90)
Pen.forward(200)
Pen.right(90)
Pen.forward(60)
Pen.right(90)
Pen.forward(20)
Pen.right(90)
Pen.forward(40)
Pen.left(90)
Pen.forward(160)
Pen.left(90)
Pen.forward(40)
Pen.right(90)
Pen.forward(20)
Pen.end_fill()
Pen.penup()
Pen.backward(140)
Pen.dot(30)
Pen.forward(40)
Pen.dot(30)
Pen.right(90)
Pen.forward(200)
Pen.left(90)
Pen.forward(430)
Pen.left(90)
Pen.pendown()
Pen.forward(20)
Pen.right(90)
Pen.begin_fill()
for i in range(4):
    Pen.forward(100)
    Pen.right(90)
Pen.end_fill()
Pen.penup()
Pen.right(90)
Pen.forward(20)
Pen.left(90)
Pen.pendown()
Pen.forward(70)
Pen.fillcolor(ColorBG)
Pen.begin_fill()
for i in range(4):
    Pen.right(90)
    Pen.forward(50)
Pen.end_fill()
Pen.backward(70)
Pen.right(90)
Pen.forward(20)
Pen.right(90)
Pen.fillcolor(ColorLine)
Pen.begin_fill()
Pen.forward(80)
Pen.right(90)
Pen.forward(40)
Pen.left(90)
Pen.forward(20)
Pen.left(90)
Pen.forward(30)
Pen.right(90)
Pen.forward(30)
Pen.right(90)
Pen.forward(90)
Pen.left(90)
Pen.forward(20)
Pen.left(90)
Pen.forward(130)
Pen.left(90)
Pen.forward(150)
Pen.end_fill()
Pen.penup()
Pen.backward(120)
Pen.right(90)
Pen.forward(30)
Pen.dot(30)
Pen.right(90)
Pen.forward(80)
Pen.pendown()
Pen.right(90)
Pen.begin_fill()
Pen.forward(70)
Pen.left(90)
Pen.forward(20)
Pen.left(90)
Pen.forward(130)
Pen.right(90)
Pen.forward(60)
Pen.left(90)
Pen.forward(20)
Pen.left(90)
Pen.forward(80)
Pen.left(90)
Pen.forward(100)
Pen.penup()
Pen.left(90)
Pen.end_fill()
Pen.forward(100)
Pen.right(90)
Pen.pendown()
Pen.begin_fill()
Pen.forward(80)
Pen.right(50)
Pen.forward(100)
Pen.left(90)
Pen.forward(20)
Pen.left(90)
Pen.forward(115)
Pen.left(50)
Pen.forward(100)
Pen.right(90)
Pen.forward(100)
Pen.right(90)
Pen.forward(20)
for i in range(2):
    Pen.left(90)
    Pen.forward(20)
Pen.forward(20)
Pen.left(90)
Pen.forward(145)
Pen.end_fill()
Pen.penup()
Pen.goto(0, -200)
if Name == "سلام" or Name == "salam":
    EasterEgg()
else:
    Pen.write(f"{Name} جان", align="left", font=("Arial", 30))
Pen.goto(-280, -350)
Pen.write(f"انشالله صد سال زنده باشی", align="left", font=("Arial", 50))
turtle.done()
